name: ci
on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        ghc: ['latest', '9.0.1', '8.10.7', '8.8.4']
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1.2.7
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
    - uses: actions/cache@v2.1.6
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}
    - name: Build
      run: |
        cabal update
        cabal v1-install --only-dependencies --enable-tests
        cabal v1-configure --enable-tests
        cabal v1-test
    - name: Haddock
      run: cabal haddock
